name: Init repo
on: create
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace README.md
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "gladier-client-template"
          replace: ${{ github.event.repository.name }}
          include: "README.md" # Will match all README.md files in any nested directory